### PR TITLE
updates for python 2.4

### PR DESCRIPTION
**Pull request by guzzijones**
changes to __encode 
changes to __number

### CODE REVIEW

**Comment by Mause** [comment]
In all fairness, that exception instance is never used anywhere, so why retrieve it at all?
Secondly, I would recommend resubmitting a new PR where you don't change the indentation style from 4-space indentation to tabbed indentation

**Comment by Mause** [comment]
Also, in your replacement of the ternary operator in the list comprehension, you forgot to add the result of `self.__encode(v)` to `listtmp` (which should probably be called `contents` owing to its purpose)

**Comment by guzzijones** [comment]
ok thank you @Mause I will work on those changes.
I will adjust my code to use the 4 space indentation rather than tabbed.
I will add the result of self.__encode(v) to listtmp and rename listtmp to contents.

**Comment by guzzijones** [comment]
@Mause I adjusted my pull request.  Let me know if you see the changes.  I am new to github and python.

**Pull request closed without merging**
